# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.tutoringhub: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: supervisorconfirmation-db
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  lessons-service:
    host: localhost
    port: 7001
  students-service:
    host: localhost
    port: 7002
  tutors-service:
    host: localhost
    port: 7003

---
spring:
  config:
    activate:
      on-profile: docker
spring.data.mongodb.host: mongodb
spring.data.mongodb.port: 27017

app:
  lessons-service:
    host: lessons-service
    port: 8080
  students-service:
    host: students-service
    port: 8080
  tutors-service:
    host: tutors-service
    port: 8080


server.port: 8080